// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paymentProto.proto

/*
Package paymentProto is a generated protocol buffer package.

It is generated from these files:
	paymentProto.proto

It has these top-level messages:
	PayInvoke
	PayRequestParams
	QueryDetailParams
	QueryAgentPayRefundParams
*/
package paymentProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InvokeMode int32

const (
	InvokeMode_SYNC  InvokeMode = 0
	InvokeMode_ASYNC InvokeMode = 1
)

var InvokeMode_name = map[int32]string{
	0: "SYNC",
	1: "ASYNC",
}
var InvokeMode_value = map[string]int32{
	"SYNC":  0,
	"ASYNC": 1,
}

func (x InvokeMode) String() string {
	return proto.EnumName(InvokeMode_name, int32(x))
}
func (InvokeMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Status int32

const (
	Status_PROCESSING Status = 0
	Status_SUCCESSED  Status = 1
	Status_FAILED     Status = 2
	Status_ACCEPTED   Status = 3
)

var Status_name = map[int32]string{
	0: "PROCESSING",
	1: "SUCCESSED",
	2: "FAILED",
	3: "ACCEPTED",
}
var Status_value = map[string]int32{
	"PROCESSING": 0,
	"SUCCESSED":  1,
	"FAILED":     2,
	"ACCEPTED":   3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PayInvokeMethod int32

const (
	PayInvokeMethod_PAY_REQUEST_METHOD PayInvokeMethod = 0
	PayInvokeMethod_QUERY_METHOD       PayInvokeMethod = 1
)

var PayInvokeMethod_name = map[int32]string{
	0: "PAY_REQUEST_METHOD",
	1: "QUERY_METHOD",
}
var PayInvokeMethod_value = map[string]int32{
	"PAY_REQUEST_METHOD": 0,
	"QUERY_METHOD":       1,
}

func (x PayInvokeMethod) String() string {
	return proto.EnumName(PayInvokeMethod_name, int32(x))
}
func (PayInvokeMethod) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PayInvoke struct {
	Method PayInvokeMethod `protobuf:"varint,1,opt,name=method,enum=PayInvokeMethod" json:"method,omitempty"`
	Params []byte          `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *PayInvoke) Reset()                    { *m = PayInvoke{} }
func (m *PayInvoke) String() string            { return proto.CompactTextString(m) }
func (*PayInvoke) ProtoMessage()               {}
func (*PayInvoke) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PayInvoke) GetMethod() PayInvokeMethod {
	if m != nil {
		return m.Method
	}
	return PayInvokeMethod_PAY_REQUEST_METHOD
}

func (m *PayInvoke) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

type PayRequestParams struct {
	TransId     string     `protobuf:"bytes,1,opt,name=transId" json:"transId,omitempty"`
	Amount      uint64     `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	MhtField    string     `protobuf:"bytes,3,opt,name=mhtField" json:"mhtField,omitempty"`
	Router      string     `protobuf:"bytes,4,opt,name=router" json:"router,omitempty"`
	Mode        InvokeMode `protobuf:"varint,5,opt,name=mode,enum=InvokeMode" json:"mode,omitempty"`
	ChannelType string     `protobuf:"bytes,6,opt,name=channelType" json:"channelType,omitempty"`
}

func (m *PayRequestParams) Reset()                    { *m = PayRequestParams{} }
func (m *PayRequestParams) String() string            { return proto.CompactTextString(m) }
func (*PayRequestParams) ProtoMessage()               {}
func (*PayRequestParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PayRequestParams) GetTransId() string {
	if m != nil {
		return m.TransId
	}
	return ""
}

func (m *PayRequestParams) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PayRequestParams) GetMhtField() string {
	if m != nil {
		return m.MhtField
	}
	return ""
}

func (m *PayRequestParams) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

func (m *PayRequestParams) GetMode() InvokeMode {
	if m != nil {
		return m.Mode
	}
	return InvokeMode_SYNC
}

func (m *PayRequestParams) GetChannelType() string {
	if m != nil {
		return m.ChannelType
	}
	return ""
}

type QueryDetailParams struct {
	AppId   string `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	TransId string `protobuf:"bytes,2,opt,name=transId" json:"transId,omitempty"`
	Router  string `protobuf:"bytes,3,opt,name=router" json:"router,omitempty"`
}

func (m *QueryDetailParams) Reset()                    { *m = QueryDetailParams{} }
func (m *QueryDetailParams) String() string            { return proto.CompactTextString(m) }
func (*QueryDetailParams) ProtoMessage()               {}
func (*QueryDetailParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryDetailParams) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *QueryDetailParams) GetTransId() string {
	if m != nil {
		return m.TransId
	}
	return ""
}

func (m *QueryDetailParams) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

type QueryAgentPayRefundParams struct {
	AppId      string `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	TransId    string `protobuf:"bytes,2,opt,name=transId" json:"transId,omitempty"`
	NowPage    uint64 `protobuf:"varint,3,opt,name=nowPage" json:"nowPage,omitempty"`
	PageSize   uint64 `protobuf:"varint,4,opt,name=pageSize" json:"pageSize,omitempty"`
	RefundDate string `protobuf:"bytes,5,opt,name=refundDate" json:"refundDate,omitempty"`
}

func (m *QueryAgentPayRefundParams) Reset()                    { *m = QueryAgentPayRefundParams{} }
func (m *QueryAgentPayRefundParams) String() string            { return proto.CompactTextString(m) }
func (*QueryAgentPayRefundParams) ProtoMessage()               {}
func (*QueryAgentPayRefundParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryAgentPayRefundParams) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *QueryAgentPayRefundParams) GetTransId() string {
	if m != nil {
		return m.TransId
	}
	return ""
}

func (m *QueryAgentPayRefundParams) GetNowPage() uint64 {
	if m != nil {
		return m.NowPage
	}
	return 0
}

func (m *QueryAgentPayRefundParams) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *QueryAgentPayRefundParams) GetRefundDate() string {
	if m != nil {
		return m.RefundDate
	}
	return ""
}

func init() {
	proto.RegisterType((*PayInvoke)(nil), "PayInvoke")
	proto.RegisterType((*PayRequestParams)(nil), "PayRequestParams")
	proto.RegisterType((*QueryDetailParams)(nil), "QueryDetailParams")
	proto.RegisterType((*QueryAgentPayRefundParams)(nil), "QueryAgentPayRefundParams")
	proto.RegisterEnum("InvokeMode", InvokeMode_name, InvokeMode_value)
	proto.RegisterEnum("Status", Status_name, Status_value)
	proto.RegisterEnum("PayInvokeMethod", PayInvokeMethod_name, PayInvokeMethod_value)
}

func init() { proto.RegisterFile("paymentProto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x8f, 0xd2, 0x40,
	0x14, 0xc7, 0x29, 0x94, 0x2e, 0x7d, 0x8b, 0xeb, 0xf8, 0x62, 0x36, 0xd5, 0x83, 0x22, 0x27, 0xc2,
	0x81, 0x83, 0x1e, 0x3d, 0x35, 0xed, 0xac, 0x92, 0xc8, 0x6e, 0x99, 0xc2, 0x81, 0x78, 0xd8, 0x8c,
	0xf6, 0x09, 0x44, 0xda, 0xa9, 0x65, 0xaa, 0xa9, 0xdf, 0xc6, 0xcf, 0xe1, 0x97, 0x33, 0x1d, 0x0a,
	0x12, 0xbd, 0xed, 0xa5, 0xe9, 0xef, 0xff, 0xf2, 0xde, 0xfb, 0xcf, 0x7f, 0x06, 0x30, 0x97, 0x55,
	0x4a, 0x99, 0x8e, 0x0a, 0xa5, 0xd5, 0x24, 0xaf, 0xbf, 0xc3, 0x19, 0xb8, 0x91, 0xac, 0xa6, 0xd9,
	0x77, 0xf5, 0x95, 0x70, 0x04, 0x4e, 0x4a, 0x7a, 0xa3, 0x12, 0xcf, 0x1a, 0x58, 0xa3, 0xab, 0xd7,
	0x6c, 0x72, 0xaa, 0xcd, 0x8c, 0x2e, 0x9a, 0x3a, 0x5e, 0x83, 0x93, 0xcb, 0x42, 0xa6, 0x7b, 0xaf,
	0x3d, 0xb0, 0x46, 0x7d, 0xd1, 0xd0, 0xf0, 0xb7, 0x05, 0x2c, 0x92, 0x95, 0xa0, 0x6f, 0x25, 0xed,
	0x75, 0x64, 0x44, 0xf4, 0xe0, 0x42, 0x17, 0x32, 0xdb, 0x4f, 0x0f, 0x73, 0x5d, 0x71, 0xc4, 0x7a,
	0x8c, 0x4c, 0x55, 0x99, 0x69, 0x33, 0xc6, 0x16, 0x0d, 0xe1, 0x73, 0xe8, 0xa5, 0x1b, 0x7d, 0xb3,
	0xa5, 0x5d, 0xe2, 0x75, 0x4c, 0xcb, 0x89, 0xeb, 0x9e, 0x42, 0x95, 0x9a, 0x0a, 0xcf, 0x36, 0x95,
	0x86, 0xf0, 0x25, 0xd8, 0xa9, 0x4a, 0xc8, 0xeb, 0x1a, 0xeb, 0x97, 0x93, 0xc6, 0xb7, 0x4a, 0x48,
	0x98, 0x02, 0x0e, 0xe0, 0xf2, 0xf3, 0x46, 0x66, 0x19, 0xed, 0x16, 0x55, 0x4e, 0x9e, 0x63, 0xba,
	0xcf, 0xa5, 0xe1, 0x47, 0x78, 0x32, 0x2f, 0xa9, 0xa8, 0x42, 0xd2, 0x72, 0xbb, 0x6b, 0xdc, 0x3f,
	0x85, 0xae, 0xcc, 0xf3, 0x93, 0xf7, 0x03, 0x9c, 0x9f, 0xa9, 0xfd, 0xdf, 0x99, 0x1a, 0x7f, 0x9d,
	0x73, 0x7f, 0xc3, 0x5f, 0x16, 0x3c, 0x33, 0xd3, 0xfd, 0x75, 0x7d, 0x07, 0x75, 0x48, 0x5f, 0xca,
	0x2c, 0x79, 0xe0, 0x16, 0x0f, 0x2e, 0x32, 0xf5, 0x23, 0x92, 0x6b, 0x32, 0x6b, 0x6c, 0x71, 0xc4,
	0x3a, 0xbb, 0x5c, 0xae, 0x29, 0xde, 0xfe, 0x24, 0x93, 0x90, 0x2d, 0x4e, 0x8c, 0x2f, 0x00, 0x0a,
	0xb3, 0x35, 0x94, 0xfa, 0x90, 0x94, 0x2b, 0xce, 0x94, 0xf1, 0x2b, 0x80, 0xbf, 0xb1, 0x61, 0x0f,
	0xec, 0x78, 0x75, 0x1b, 0xb0, 0x16, 0xba, 0xd0, 0xf5, 0xcd, 0xaf, 0x35, 0xf6, 0xc1, 0x89, 0xb5,
	0xd4, 0xe5, 0x1e, 0xaf, 0x00, 0x22, 0x71, 0x17, 0xf0, 0x38, 0x9e, 0xde, 0xbe, 0x63, 0x2d, 0x7c,
	0x04, 0x6e, 0xbc, 0x0c, 0x6a, 0xe6, 0x21, 0xb3, 0x10, 0xc0, 0xb9, 0xf1, 0xa7, 0x1f, 0x78, 0xc8,
	0xda, 0xd8, 0x87, 0x9e, 0x1f, 0x04, 0x3c, 0x5a, 0xf0, 0x90, 0x75, 0xc6, 0x6f, 0xe1, 0xf1, 0x3f,
	0xef, 0x0a, 0xaf, 0x01, 0x23, 0x7f, 0x75, 0x2f, 0xf8, 0x7c, 0xc9, 0xe3, 0xc5, 0xfd, 0x8c, 0x2f,
	0xde, 0xdf, 0x85, 0xac, 0x85, 0x0c, 0xfa, 0xf3, 0x25, 0x17, 0xab, 0xa3, 0x62, 0x7d, 0x72, 0xcc,
	0xbb, 0x7d, 0xf3, 0x27, 0x00, 0x00, 0xff, 0xff, 0x46, 0xeb, 0x4a, 0xb1, 0xcd, 0x02, 0x00, 0x00,
}
